version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: jujuy-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jujuy_market
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  migrate-products:
    image: migrate/migrate
    container_name: migrate-products
    volumes:
      - ./migrations/products:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@postgres:5432/jujuy_market?sslmode=disable",
      "up"
    ]
    depends_on:
      - postgres
    restart: "no"

  migrate-users:
    image: migrate/migrate
    container_name: migrate-users
    volumes:
      - ./migrations/users:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@postgres:5432/jujuy_market?sslmode=disable",
      "up"
    ]
    depends_on:
      - postgres
    restart: "no"

  products:
    image: juancanchi/products:latest
    container_name: jujuy-products
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - JWT_SECRET=supersecreto
      - DB_DSN=host=postgres user=postgres password=postgres dbname=jujuy_market port=5432 sslmode=disable
    depends_on:
      - postgres

volumes:
  pgdata: